### PR TITLE
Fix Error Messages with Extra Closing Parentheses  closes #182

### LINKED ISSUE #182: 🚀 Fix Error Messages with Extra Closing Parentheses
Issue: Some functions like `direct_dependencies_operator function` in the `handler.py` has error messages that include an extra closing parenthesis.

Task: Look through the error messages. Remove the redundant closing parenthesis to correct the error messages.

### PR DESCRIPTION
**Pull request by zafar-hussain**
Hi,

This PR closes #182,

Extra Closing Parentheses were removed from 4 points in handler.py and 1 in test_direct_references.py

cheers

### CODE REVIEW

**Comment by AkashS0510** [comment]
Thanks for the PR @zafar-hussain . Can you squash the commits into a single one and put a commit description about the changes you made?

**Review by AkashS0510 — APPROVED** [review]

**Comment by zafar-hussain** [comment]
Hi @AkashS0510 

Thanks for the reply,


Mistakenly, I have pushed two separate commits together, first one was for issue #182 and the second (incorrectly included) was meant for issue #180

I am failing in finding a way to undo it.

Please, if you can guide me to cancel this PR, or remove the second commit

I will push separate PRs again

thanks 
zafar

**Comment by AkashS0510** [comment]
@zafar-hussain Maybe you can close this PR and create 2 new PRs from 2 different branches for the two issues.

**Comment by zafar-hussain** [comment]
Wrong commits merged together

**Pull request closed without merging**
