### PR TITLE
Simplify type checking in sort_collections()  Closes https://github.com/StackGuardian/tirith/issues/185

### PR DESCRIPTION
**Pull request by gabrilito1**
Update the sort_collections function in the utils.py to use a single isinstance check for primitive types.

### CODE REVIEW

**Review by refeed — CHANGES_REQUESTED** [review]
Hi @gabrilito1 , thanks this looks good.

Only a few minor things though:
1. Could you fix the [linting warnings ](https://github.com/StackGuardian/tirith/actions/runs/11085391404/job/30806291643?pr=186) by running black in your system?
2. Could you make your commit message into:
```
Simplify type checking in sort_collections()

Closes https://github.com/StackGuardian/tirith/issues/185
```

**Comment by gabrilito1** [comment]
Done, give me a feedback asap

**Review by refeed — APPROVED** [review]
Looks good, I'll just do squash and rebase on this commit. Thanks!

**Comment by refeed** [comment]
BTW @gabrilito1 , I forgot to mention that what I meant by the commit message is the git commit message. Ideally, we could squash the commits into one and then use `git commit --amend` to change the commit message and then do force push again. But for now, it's fine, we'll do it on our side, but if you want to change the commit message, feel free to do so

**Review by samriddhi99 — APPROVED** [review]
LGTM

**Pull request merged**
