### PR TITLE
Centralized version definition to simplify version bumping process

### PR DESCRIPTION
**Pull request by ANISH-SR**
This PR aims to enhance our version management process by centralizing the version definition, making it easier to bump versions across the project.

Current behavior:
The version number is defined in multiple places across the project, including 'cli.py' and '__init__.py'. When bumping the version, we need to search and replace the version string in all these files.

Proposed change:
1. Centralize the version definition in a single location (i.e, '__init__.py').
2. Update other modules, such as 'cli.py', to import and use the centralized version definition.

### CODE REVIEW

**Comment by ANISH-SR** [comment]
Hi @refeed , could you please review this enhancement. Please tell me if anything else is needed to be fixed here.
Thanks

**Comment by refeed** [comment]
Thanks for the contribution! the changes looks good, btw could you please rename the commit message into something more descriptive? `git commit --amend` will be useful for this

**Review by samriddhi99 — APPROVED** [review]
Thank you for your contribution! LGTM.

**Review by refeed — APPROVED** [review]
LGTM

**Pull request merged**
